//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModels.ApfBaseEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApfBaseContext : DbContext
    {
        public ApfBaseContext()
            : base("name=ApfBaseContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AggregatedEquipment> AggregatedEquipment { get; set; }
        public virtual DbSet<Annex> Annex { get; set; }
        public virtual DbSet<AnnexVsBranchGroup> AnnexVsBranchGroup { get; set; }
        public virtual DbSet<AOPO> AOPO { get; set; }
        public virtual DbSet<AOSN> AOSN { get; set; }
        public virtual DbSet<APF> APF { get; set; }
        public virtual DbSet<APNU> APNU { get; set; }
        public virtual DbSet<ARPM> ARPM { get; set; }
        public virtual DbSet<BoundingElements> BoundingElements { get; set; }
        public virtual DbSet<BranchGroup> BranchGroup { get; set; }
        public virtual DbSet<BranchGroupScheme> BranchGroupScheme { get; set; }
        public virtual DbSet<BranchGroupVsBranchGroupScheme> BranchGroupVsBranchGroupScheme { get; set; }
        public virtual DbSet<Conditions> Conditions { get; set; }
        public virtual DbSet<Disturbances> Disturbances { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<EquipmentVsInfluencingEquipment> EquipmentVsInfluencingEquipment { get; set; }
        public virtual DbSet<FrequencyPowerFlow> FrequencyPowerFlow { get; set; }
        public virtual DbSet<InfluencingEquipment> InfluencingEquipment { get; set; }
        public virtual DbSet<Management> Management { get; set; }
        public virtual DbSet<ManagementTasks> ManagementTasks { get; set; }
        public virtual DbSet<Performers> Performers { get; set; }
        public virtual DbSet<PostFaultConditions> PostFaultConditions { get; set; }
        public virtual DbSet<PreFaultConditions> PreFaultConditions { get; set; }
        public virtual DbSet<Seasons> Seasons { get; set; }
        public virtual DbSet<Temperature> Temperature { get; set; }
    }
}
