//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModels.ApfBaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conditions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conditions()
        {
            this.FrequencyPowerFlow = new HashSet<FrequencyPowerFlow>();
            this.PostFaultConditions = new HashSet<PostFaultConditions>();
            this.PreFaultConditionsCurrent = new HashSet<PreFaultConditions>();
            this.PreFaultConditionsStatic = new HashSet<PreFaultConditions>();
            this.PreFaultConditionsVoltage = new HashSet<PreFaultConditions>();
        }
    
        public int Id { get; set; }
        public Nullable<System.Guid> BranchGroupUid { get; set; }
        public string Name { get; set; }
        public string FormalName { get; set; }
        public Nullable<double> MinValue { get; set; }
        public Nullable<double> MaxValue { get; set; }
    
        public virtual BranchGroup BranchGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrequencyPowerFlow> FrequencyPowerFlow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostFaultConditions> PostFaultConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreFaultConditions> PreFaultConditionsCurrent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreFaultConditions> PreFaultConditionsStatic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreFaultConditions> PreFaultConditionsVoltage { get; set; }
    }
}
