//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModels.ApfBaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAR()
        {
            this.PostFaultConditions = new HashSet<PostFaultConditions>();
        }
    
        public int Id { get; set; }
        public Nullable<System.Guid> BranchGroupUid { get; set; }
        public Nullable<int> SeasonsId { get; set; }
        public string Name { get; set; }
        public string FormalName { get; set; }
        public Nullable<double> ControlValuePowerFlow { get; set; }
        public Nullable<double> Coefficient { get; set; }
    
        public virtual BranchGroup BranchGroup { get; set; }
        public virtual Seasons Seasons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostFaultConditions> PostFaultConditions { get; set; }
    }
}
