//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModels.ApfBaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostFaultConditions
    {
        public int BranchGroupVsBranchGroupSchemeId { get; set; }
        public int PreFaultConditionsId { get; set; }
        public int Id { get; set; }
        public Nullable<int> DisturbancesId { get; set; }
        public Nullable<int> BoundingElementsId { get; set; }
        public Nullable<int> AopoId { get; set; }
        public Nullable<int> ApnuId { get; set; }
        public Nullable<int> ArpmId { get; set; }
        public Nullable<int> AosnId { get; set; }
        public Nullable<int> DarId { get; set; }
        public Nullable<int> ConditionsId { get; set; }
        public Nullable<int> FrequencyPowerFlowId { get; set; }
        public Nullable<bool> Using { get; set; }
        public Nullable<double> EprPowerFlow { get; set; }
        public Nullable<double> DynamicPowerFlow { get; set; }
        public Nullable<double> CurrentPowerFlow { get; set; }
        public Nullable<double> CurrentAOPO { get; set; }
        public Nullable<double> VoltagePowerFlow { get; set; }
        public string Comment { get; set; }
    
        public virtual AOPO AOPO { get; set; }
        public virtual AOSN AOSN { get; set; }
        public virtual APNU APNU { get; set; }
        public virtual ARPM ARPM { get; set; }
        public virtual BoundingElements BoundingElements { get; set; }
        public virtual Conditions Conditions { get; set; }
        public virtual DAR DAR { get; set; }
        public virtual Disturbances Disturbances { get; set; }
        public virtual FrequencyPowerFlow FrequencyPowerFlow { get; set; }
        public virtual PreFaultConditions PreFaultConditions { get; set; }
    }
}
